server:
  port: 9090

spring:
  datasource:
    url: jdbc:postgresql://localhost:5434/blog-cubetiq-db
    username: blog-cubetiq-db
    password: 123456
    driver-class-name: org.postgresql.Driver
  jpa:
    database: postgresql
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
